version: '3'

services:
  trading-front:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
